name: Web Api Automation Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run API Tests
        run: ./gradlew clean test

  web-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run Web Automation
        run: ./gradlew clean test

      - name: Upload Web Report
        uses: actions/upload-artifact@v4
        with:
          name: web-cucumber-report
          path: target/